export const AppRoutes = {
  HOME: "/",
  PROJECT: "/project",
  DATASET: "/data-set",
  CONTAINER: "/container",
  COMPUTE: "/compute",
  LOGIN: "/login",
  STARTPROJECT: "start-project",
  PROJECT_PAGE: ":name",
  ADDFILETOPROJECT: "addFileToProject",
  VIEWANDADDNEWFILETOPROJECT: "viewAndAddFileToProject",
  WORKSPACE: "workspace",
  PROGRESS: "workspace/progress",
  EXPERIMENT: "experiment",
  SETTING: "setting",
  SERVING: "serving",
  GENERAL: "general",
  INFO: "info",
  COMMIT: "commit",
  REGISTRY: "registry",
  BUILDIMG: "build-img",
  TEMPLATE: "template",
  RESOURCE: "resource",
  STORAGE: "storage",
  ADD_NEW_TEMPLATE: "add-new-template"
};
